version: '3.8'

services:
  app:
    image: node:14
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    command: npm start

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - '5432:5432'

  redis:
    image: redis:latest
    ports:
      - '6379:6379'

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'

  redis-commander:
    image: rediscommander/redis-commander
    environment:
      - REDIS_HOSTS=local:6379
    ports:
      - '8081:8081'